# Generated by Django 4.2.7 on 2023-11-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horarioInicio', models.TimeField()),
                ('horarioTermino', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduleManagement.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('disciplinas', models.ManyToManyField(to='scheduleManagement.disciplina')),
                ('horario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduleManagement.horario')),
            ],
        ),
    ]
