# Generated by Django 4.2.7 on 2023-12-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleManagement', '0002_rename_horarioinicio_horario_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
