name: Django CI

on: [push, pull_request]

jobs: # The job contains process, and this process contains steps
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up Python 3.12.0
      uses: actions/setup-python@v3 
      with:
        python-version: 3.12.0

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Testing Secret KEY
      run: echo "Secret Key is ${{ secrets.TEST }}"
